// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdg2gklX1EdYNrA6KWODgCclx0arporZU',
    appId: '1:1076321563098:web:a9c1b6daf60590d12450e3',
    messagingSenderId: '1076321563098',
    projectId: 'cothia',
    authDomain: 'cothia.firebaseapp.com',
    storageBucket: 'cothia.firebasestorage.app',
    measurementId: 'G-M16N5KVJSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwEWjxkYpE0zJ4TrqFPLIh7U1ld_cOtM',
    appId: '1:1076321563098:android:a272ef8eee73d2b72450e3',
    messagingSenderId: '1076321563098',
    projectId: 'cothia',
    storageBucket: 'cothia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3n489PkDei2b3cHVJaQDeU17CgkoDqk',
    appId: '1:1076321563098:ios:6c4f41bfbe1ba13e2450e3',
    messagingSenderId: '1076321563098',
    projectId: 'cothia',
    storageBucket: 'cothia.firebasestorage.app',
    iosBundleId: 'com.menosi.cothiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ3n489PkDei2b3cHVJaQDeU17CgkoDqk',
    appId: '1:1076321563098:ios:6c4f41bfbe1ba13e2450e3',
    messagingSenderId: '1076321563098',
    projectId: 'cothia',
    storageBucket: 'cothia.firebasestorage.app',
    iosBundleId: 'com.menosi.cothiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdg2gklX1EdYNrA6KWODgCclx0arporZU',
    appId: '1:1076321563098:web:4c68974314d866912450e3',
    messagingSenderId: '1076321563098',
    projectId: 'cothia',
    authDomain: 'cothia.firebaseapp.com',
    storageBucket: 'cothia.firebasestorage.app',
    measurementId: 'G-RW4WHLNZKN',
  );
}
